[package]
name = "gyroflow-ofx"
version = "0.1.0"
authors = ["Ilya Epifanov <elijah.epifanov@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name="gyroflow_ofx"
crate-type = ["cdylib"]
path="src/lib.rs"

[dependencies]
ofx = "0.3"
opencv = { version = "0.52", features = ["clang-runtime"] }
cgmath = "0.18.0"

[patch.crates-io]
ofx = { git = "https://github.com/ilya-epifanov/ofx-rs.git", rev = "211f74c7d2955e5c53166af4f2a00f35ae6a363a" }
ofx_sys = { git = "https://github.com/ilya-epifanov/ofx-rs.git", rev = "211f74c7d2955e5c53166af4f2a00f35ae6a363a" }
