[package]
name = "gyroflow-ofx"
version = "1.0.0"
authors = ["Ilya Epifanov <elijah.epifanov@gmail.com>"]
license = "GPL-3.0-or-later AND (MIT OR Apache-2.0)"
edition = "2021"
description = "GyroFlow OpenFX plugin"

[lib]
name="gyroflow_ofx"
crate-type = ["cdylib"]
path="src/lib.rs"

[dependencies]
ofx = "0.3"
nalgebra = "0.26"
measure_time = "0.6"
log = "0.4"
itertools = "*"
rayon = "*"
ndarray = { version = "0.15", features = ["rayon"] }
float-ord = "0.3.2"
lru = "0.7"
gyroflow-core = { path = "gyroflow/src/core/", default-features = false, version = "1.0.0-rc1" }
serde_json = "1"

[features]
default = ["use-opencl"]
use-opencl = ["gyroflow-core/use-opencl"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[patch.crates-io]
ofx = { git = "https://github.com/ilya-epifanov/ofx-rs.git", rev = "79d1f4a006f60430d4333f2125d8b3236d6a9ccd" }
ofx_sys = { git = "https://github.com/ilya-epifanov/ofx-rs.git", rev = "79d1f4a006f60430d4333f2125d8b3236d6a9ccd" }
